language: c

compiler:
    - gcc
    - clang

dist: trusty

sudo: required

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential cmake clang

install: ./scripts/install-deps.sh

script: ./scripts/travis-build.sh
